
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                            0
#define PARTNER_STEVEN_SOUTHERN_ISLAND          1
#define PARTNER_WALLY_AQUA_HIDEOUT              2
#define PARTNER_BRENDAN_MAGMA_HIDEOUT_TREECKO   3
#define PARTNER_BRENDAN_MAGMA_HIDEOUT_TORCHIC   4
#define PARTNER_BRENDAN_MAGMA_HIDEOUT_MUDKIP    5
#define PARTNER_MAY_MAGMA_HIDEOUT_TREECKO       6
#define PARTNER_MAY_MAGMA_HIDEOUT_TORCHIC       7
#define PARTNER_MAY_MAGMA_HIDEOUT_MUDKIP        8
#define PARTNER_STEVEN                          9

#define PARTNER_COUNT                           10
//Tests need PARTNER_COUNT to be at least 3 so we add a dummy partner

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
