
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN_2            1
#define PARTNER_STEVEN              2

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
