MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a POKéMON of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which POKéMON wants to\n"
	.string "learn how to SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your POKéMON will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a BUG-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called FURY CUTTER.\n"
	.string "Want me to teach it to a POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach MIMIC\n"
	.string "to your POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the POKéMON\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife is always full of\n"
	.string "energy, a real TRAILBLAZE.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to\n"
	.string "SLEEP TALK instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with TRAILBLAZE, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"

MoveTutor_Text_DracoMeteorTeach:
	.string "Hohoho…\n"
	.string "For you to find your way here, you\l"
	.string "must be an accomplished trainer.\p"
	.string "I can teach your DRAGON POKéMON the\n"
	.string "ultimate DRAGON move.\p"
	.string "Would you like to learn how to use\n"
	.string "the move DRACO METEOR?$"

MoveTutor_Text_DracoMeteorDeclined:
	.string "Not interested?\n"
	.string "Well, you know where to find me if\l"
	.string "you change your mind.$"

MoveTutor_Text_DracoMeteorWhichMon:
	.string "Very well!\n"
	.string "Which POKéMON shall gain this power?$"

MoveTutor_Text_DracoMeteorTaught:
	.string "Now, I wonder how far you will go\n"
	.string "with this power…?\p"
	.string "The best of luck to you…$"

MoveTutor_Text_SteelBeamTeach:
	.string "Huh?!\n"
	.string "Why is there another person here?!\p"
	.string "I went to the middle of the ocean and\n"
	.string "even hid in this old ship, and yet\l"
	.string "I still can't find somewhere quiet?\p"
	.string "You! If you leave me alone, I will\n"
	.string "teach your STEEL POKéMON the ultimate\l"
	.string "STEEL move! Does that sound fair?$"

MoveTutor_Text_SteelBeamDeclined:
	.string "No?!\n"
	.string "Why is it so hard to get some peace?!$"

MoveTutor_Text_SteelBeamWhichMon:
	.string "Fine! Here we go!\n"
	.string "Which POKéMON is learning this move?$"

MoveTutor_Text_SteelBeamTaught:
	.string "There! Now scram!\n"
	.string "My favourite anime is about to begin\l"
	.string "and I need these chambers to myself!\p"
	.string "For, uh, personal reasons!$"

MoveTutor_Text_PledgeTeach:
	.string "Many, many years ago, me and my wife\n"
	.string "made a pledge to each other to stay\l"
	.string "together, through thick and thin.\p"
	.string "Even though she may be gone, I know\n"
	.string "even now she is still watching me.\p"
	.string "If you would like, I can teach your\n"
	.string "POKéMON how to make a pledge as well.$"

MoveTutor_Text_PledgeSelect:
	.string "Which pledge are you interested in\n"
	.string "having your POKéMON learn?$"

MoveTutor_Text_PledgeDeclined:
	.string "Ah, perhaps another time then.\n"
	.string "Please, do make the most of the time\l"
	.string "you spend with your loved ones.$"

MoveTutor_Text_PledgeWhichMon:
	.string "A fine choice.\n"
	.string "Which POKéMON will be learning this?$"

MoveTutor_Text_PledgeTaught:
	.string "One day, in the not so distant future\n"
	.string "I will see my wife once again.\p"
	.string "I hope that even if I depart from this\n"
	.string "world, the wishes I have bestowed upon\l"
	.string "you will help just a small part of both\l"
	.string "me and my wife live on within you.\p"
	.string "Take care of yourself, young TRAINER.\n"
	.string "And remember to treasure every moment\l"
	.string "you spend with those you care about.$"

MoveTutor_Text_UltimateMoveTeach:
	.string "I'm just getting ready to take on\n"
	.string "VICTORY ROAD, and soon after the\l"
	.string "POKéMON LEAGUE.\p"
	.string "With these ultimate techniques I have\n"
	.string "been practicing, the ELITE FOUR surely\l"
	.string "won't stand a chance!\p"
	.string "Oh? That look in your eyes…\n"
	.string "I can tell I've caught your attention.\p"
	.string "Very well! I suppose I could maybe teach\n"
	.string "your POKéMON these moves, as well!$"

MoveTutor_Text_UltimateMoveSelect:
	.string "A smart choice, my friend! Which of these\n"
	.string "moves are you interested in?$"

MoveTutor_Text_UltimateMoveDeclined:
	.string "B-but these are the ultimate moves!\n"
	.string "Please, reconsider!$"

MoveTutor_Text_UltimateMoveWhichMon:
	.string "You have great taste!\n"
	.string "Who will be learning this ultimate move?$"

MoveTutor_Text_UltimateMoveTaught:
	.string "Excellent! With this move at your\n"
	.string "disposal, nothing stands in your way!\p"
	.string "Wait, should I be teaching powerful\n"
	.string "moves like this to my opposition…?\p"
	.string "If you beat the ELITE FOUR now, will\n"
	.string "we have to fight?\p"
	.string "Meh, I'm sure it'll work out!$"
