ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Are you planning on going deep\n"
	.string "in there?\p"
	.string "How about bringing me back some\n"
	.string "SHOAL SALT and SHOAL SHELLS?\p"
	.string "I can make you something good if\n"
	.string "you bring me the ingredients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "If you bring me four each of the\n"
	.string "SHOAL SALT and SHOAL SHELLS,\l"
	.string "I can make you a SHELL BELL…\p"
	.string "You can get those ingredients\n"
	.string "every day.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hey! SHOAL SALT and SHOAL SHELLS!\n"
	.string "And enough of them, too!\p"
	.string "Would you like me to make you\n"
	.string "a SHELL BELL with them?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "All righty, then! I'll make you\n"
	.string "a SHELL BELL right away.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "There! Done!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Have a POKéMON hold on to that.\n"
	.string "It'll love it, that's for certain.\p"
	.string "Why, the SHELL BELL's chime…\n"
	.string "It's simply sublime!\p"
	.string "You can get its ingredients every day,\n"
	.string "so I can make you more.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Is that so…\n"
	.string "I wanted to make a SHELL BELL…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "You don't have space in your BAG\n"
	.string "if I were to make it for you.\p"
	.string "You should make room and come back\n"
	.string "for a SHELL BELL.$"

ShoalCave_Text_GlalieIsTheBest:
	.string "Here in SHOAL CAVE, you can find a\n"
	.string "POKéMON called SNORUNT.\p"
	.string "SNORUNT can evolve into two different\n"
	.string "species of POKéMON.\p"
	.string "Now, any true TRAINER worth their salt\n"
	.string "knows that GLALIE is the best evolution.\p"
	.string "With its HIDDEN ABILITY, MOODY, it can\n"
	.string "snowball out of control.\p"
	.string "It even has a MEGA EVOLUTION that can\n"
	.string "turn NORMAL moves into ICE moves that\l"
	.string "really pack a punch.\p"
	.string "Now, that fool over there has the gall\n"
	.string "to insist that FROSLASS is better…\p"
	.string "What utter ignorance, I say!\p"
	.string "If you want to follow the correct path\n"
	.string "for SNORUNT, then bring me 8 SHOAL SALT.\p"
	.string "Do that, and I know I can trust you with\n"
	.string "the power of a GLALITITE.$"

ShoalCave_Text_DidYouGetShoalSalt:
	.string "Did you bring 8 SHOAL SALT to trade\n"
	.string "for a GLALITITE?$"

ShoalCave_Text_CanBeFoundInLowTide:
	.string "I understand, they can be hard to gather.\n"
	.string "You can find SHOAL SALT during low tide.\p"
	.string "You may not find enough in a single day\n"
	.string "though, so be sure to keep checking!$"

ShoalCave_Text_FroslassIsTheBest:
	.string "Here in SHOAL CAVE, you can find a\n"
	.string "POKéMON called SNORUNT.\p"
	.string "SNORUNT can evolve into two different\n"
	.string "species of POKéMON.\p"
	.string "It doesn't take a genius though to see\n"
	.string "that FROSLASS is the best evolution.\p"
	.string "The blistering speed of FROSLASS lets\n"
	.string "it get off useful support like SPIKES\l"
	.string "no problem at all.\p"
	.string "It even has a MEGA EVOLUTION with truly\n"
	.string "incredible speed and power that the\l"
	.string "other evolution can't hope to match.\p"
	.string "Now, that buffoon over there somehow\n"
	.string "believes that GLALIE is better…\p"
	.string "What complete idiocy, I say!\p"
	.string "If you want to follow the correct path\n"
	.string "for SNORUNT, then bring me 8 SHOAL SHELLS.\p"
	.string "Do that, and I know I can trust you with\n"
	.string "the power of a FROSLASSITE.$"

ShoalCave_Text_DidYouGetShoalShells:
	.string "Did you bring 8 SHOAL SHELLS to trade\n"
	.string "for a FROSLASSITE?$"

ShoalCave_Text_CanBeFoundInHighTide:
	.string "I understand, they can be hard to gather.\n"
	.string "You can find SHOAL SHELLS during high tide.\p"
	.string "You may not find enough in a single day\n"
	.string "though, so be sure to keep checking!$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "There was some SHOAL SALT here.\n"
	.string "But, there's nothing here now.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "There was a SHOAL SHELL here.\n"
	.string "But, there's nothing here now.$"
