gText_WantToUseSurf::
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to SURF?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} used SURF!$"

Text_CurrentTooFast::
	.string "The current is much too fast!\n"
	.string "SURF can't be used here…$"

gText_WantToUseBrineysKeys::
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to ride BRINEY'S BOAT?$"

gText_PlayerUsedBrineysKeys::
	.string "{PLAYER} used BRINEY'S KEYS!$"

