OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a WILD POKéMON battle starts, the\n"
	.string "one at the left of the list goes out.\p"
	.string "But in a TRAINER BATTLE, both the one\n"
	.string "at left of the list and the one on the\l"
	.string "top of the list get sent out.\p"
	.string "Try switching around the order of your\n"
	.string "POKéMON before going into battle.\p"
	.string "It could give you an advantage.$"

