TuffnookTown_House1_MapScripts::
	.byte 0

TuffnookTown_House1_EventScript_Hiker::
	msgbox TuffnookTown_House1_Text_LivedRoundHereForYears, MSGBOX_NPC
	end

TuffnookTown_House1_EventScript_Woman::
	msgbox TuffnookTown_House1_Text_MovedWithMyHusband, MSGBOX_NPC
	end

TuffnookTown_House1_Text_LivedRoundHereForYears:
	.string "I've lived round here since I was born.\p"
	.string "It can be a bit of a shock to the system\n"
	.string "at first, but I wouldn't have it any\l"
	.string "other way. I'm glad my wife agrees!$"

TuffnookTown_House1_Text_MovedWithMyHusband:
	.string "When I first moved here to live with\n"
	.string "my husband, I really wasn't sure how\l"
	.string "to feel about living in a cave.\p"
	.string "Strangely enough though, this place\n"
	.string "has really grown on me.$"
